In [ ]:
Generate complex graph for 23180 complexes...
Successfully created dataset with 23180 complexes
DataLoader created with batch size 32

=== Test Batch Info ===
Total nodes in batch: 6624
Total edges in batch: 104088
Node types: ['ligand', 'pocket']
Edge types: ['inter_l2p', 'intra_l', 'inter_p2l', 'intra_p', 'intra_p_noncov']
[NodeType: ligand] feat shape=torch.Size([961, 35])
Sample values:
tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
         0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
         1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.]])
[NodeType: pocket] feat shape=torch.Size([5663, 35])
Sample values:
tensor([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
         0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.]])
[EdgeType: inter_l2p] feat shape=torch.Size([10840, 11])
Sample values:
tensor([[0.1009, 0.0254, 0.0846, 0.7120, 0.1438, 0.4793, 0.3698, 0.0767, 0.2556,
         0.6831, 0.4884],
        [0.1414, 0.0544, 0.1088, 0.9159, 0.2923, 0.5847, 0.4725, 0.1559, 0.3118,
         0.6111, 0.4217]])
[EdgeType: intra_l] feat shape=torch.Size([2112, 17])
Sample values:
tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0457, 0.0046, 0.0457,
         0.0807, 0.0081, 0.0807, 0.2513, 0.0251, 0.2513, 0.2259, 0.1456],
        [1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0457, 0.0046, 0.0457,
         0.0807, 0.0081, 0.0807, 0.2513, 0.0251, 0.2513, 0.2259, 0.1456]])
[EdgeType: inter_p2l] feat shape=torch.Size([10840, 11])
Sample values:
tensor([[0.1250, 0.1134, 0.0756, 1.0634, 1.0654, 0.7103, 0.9503, 0.8151, 0.5434,
         0.6831, 0.4884],
        [0.1286, 0.1224, 0.0874, 0.7855, 0.7898, 0.5642, 0.8626, 0.6663, 0.4759,
         0.4572, 0.3795]])
[EdgeType: intra_p] feat shape=torch.Size([10874, 17])
Sample values:
tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.2308, 0.1464],
        [1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.2308, 0.1464]])
[EdgeType: intra_p_noncov] feat shape=torch.Size([69422, 11])
Sample values:
tensor([[0.1736, 0.0764, 0.1273, 0.4779, 0.2045, 0.3409, 0.3897, 0.1973, 0.3289,
         0.3836, 0.2462],
        [0.1508, 0.0422, 0.1054, 0.6713, 0.1708, 0.4271, 0.3897, 0.1200, 0.3000,
         0.5888, 0.3509]])
Labels shape: torch.Size([32]), sample values: tensor([5.9400, 5.7400, 8.3300, 7.3500, 6.4700])